// Generated by CoffeeScript 1.8.0
import Pretender from 'pretender';
import { RESPONSES } from '../responses/responses';

export var notLoggedInServer = function() {
  return new Pretender(function() {
    return this.get('/login', function(request) {
      return [200, {'Content-Type': 'application/json'},
              RESPONSES.login_get_notLoggedIn];
    });
  });
};

export var loggedInServer = function() {
  return new Pretender(function() {
    return this.get('/login', function(request) {
      return [200, {'Content-Type': 'application/json'},
              RESPONSES.login_get_loggedIn];
    });
  });
};